'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Images', [
      { campId: 1, url: 'frontend/public/Images/campImages/1_Syncitium-1.jpg' },
      { campId: 1, url: 'frontend/public/Images/campImages/1_Syncitium-2.jpg' },
      { campId: 1, url: 'frontend/public/Images/campImages/1_Syncitium-3.jpg' },
      { campId: 1, url: 'frontend/public/Images/campImages/1_Syncitium-4.jpg' },
      { campId: 3, url: 'frontend/public/Images/campImages/3_Transfoamation.jpg' },
      { campId: 4, url: 'frontend/public/Images/campImages/4_Camp-)?(-1.jpg' },
      { campId: 4, url: 'frontend/public/Images/campImages/4_Camp-)?(-2.jpg' },
      { campId: 5, url: 'frontend/public/Images/campImages/5_DeMentha.jpg' },
      { campId: 6, url: 'frontend/public/Images/campImages/6_Center-Camp-1.jpg' },
      { campId: 6, url: 'frontend/public/Images/campImages/6_Center-Camp-2.jpg' },
      { campId: 6, url: 'frontend/public/Images/campImages/6_Center-Camp-3.jpg' },
      { campId: 7, url: 'frontend/public/Images/campImages/7_Bubbles-and-Bass.jpg' },
      { campId: 8, url: 'frontend/public/Images/campImages/8_DISTRIKT-1.jpg' },
      { campId: 8, url: 'frontend/public/Images/campImages/8_DISTRIKT-2.jpg' },
      { campId: 9, url: 'frontend/public/Images/campImages/9_Stardust-Lounge-1.jpg' },
      { campId: 9, url: 'frontend/public/Images/campImages/9_Stardust-Lounge-2.jpg' },
      { campId: 10, url: 'frontend/public/Images/campImages/10_Mayan-Warrior-1.jpg' },
      { campId: 10, url: 'frontend/public/Images/campImages/10_Mayan-Warrior-2.jpg' },
      { campId: 10, url: 'frontend/public/Images/campImages/10_Mayan-Warrior-3.jpg' },
      { campId: 10, url: 'frontend/public/Images/campImages/10_Mayan-Warrior-4.jpg' },
      { campId: 10, url: 'frontend/public/Images/campImages/10_Mayan-Warrior-5.jpg' },
      { campId: 10, url: 'frontend/public/Images/campImages/10_Mayan-Warrior-6.jpg' },
      { campId: 10, url: 'frontend/public/Images/campImages/10_Mayan-Warrior-7.jpg' },
      { campId: 10, url: 'frontend/public/Images/campImages/10_Mayan-Warrior-8.jpg' },
      { campId: 11, url: 'frontend/public/Images/campImages/11_Play-Alchemist-1.jpg' },
      { campId: 11, url: 'frontend/public/Images/campImages/11_Play-Alchemist-2.jpg' },
      { campId: 11, url: 'frontend/public/Images/campImages/11_Play-Alchemist-3.jpg' },
      { campId: 11, url: 'frontend/public/Images/campImages/11_Play-Alchemist-4.jpg' },
      { campId: 12, url: 'frontend/public/Images/campImages/12_Incendia-1.jpg' },
      { campId: 12, url: 'frontend/public/Images/campImages/12_Incendia-2.jpg' },
      { campId: 12, url: 'frontend/public/Images/campImages/12_Incendia-3.jpg' },
      { campId: 13, url: 'frontend/public/Images/campImages/13_The-Man-1.jpg' },
      { campId: 13, url: 'frontend/public/Images/campImages/13_The-Man-2.jpg' },
      { campId: 13, url: 'frontend/public/Images/campImages/13_The-Man-3.jpg' },
      { campId: 13, url: 'frontend/public/Images/campImages/13_The-Man-4.jpg' },
      { campId: 13, url: 'frontend/public/Images/campImages/13_The-Man-5.jpg' },
      { campId: 13, url: 'frontend/public/Images/campImages/13_The-Man-6.jpg' },
      { campId: 13, url: 'frontend/public/Images/campImages/13_The-Man-7.jpg' },
      { campId: 13, url: 'frontend/public/Images/campImages/13_The-Man-8.jpg' },
      { campId: 14, url: 'frontend/public/Images/campImages/14_The-Temple-1.jpg' },
      { campId: 14, url: 'frontend/public/Images/campImages/14_The-Temple-2.jpg' },
      { campId: 14, url: 'frontend/public/Images/campImages/14_The-Temple-3.jpg' },
      { campId: 14, url: 'frontend/public/Images/campImages/14_The-Temple-4.jpg' },
      { campId: 14, url: 'frontend/public/Images/campImages/14_The-Temple-5.jpg' },
      { campId: 14, url: 'frontend/public/Images/campImages/14_The-Temple-6.jpg' },
      { campId: 15, url: 'frontend/public/Images/campImages/15_Illumina-1.jpg' },
      { campId: 15, url: 'frontend/public/Images/campImages/15_Illumina-2.jpg' },
      { campId: 15, url: 'frontend/public/Images/campImages/15_Illumina-3.jpg' },
      { campId: 15, url: 'frontend/public/Images/campImages/15_Illumina-4.jpg' },
      { campId: 16, url: 'frontend/public/Images/campImages/16_Tree-ofTenere-1.jpg' },
      { campId: 16, url: 'frontend/public/Images/campImages/16_Tree-ofTenere-2.jpg' },
      { campId: 16, url: 'frontend/public/Images/campImages/16_Tree-ofTenere-3.jpg' },
      { campId: 17, url: 'frontend/public/Images/campImages/17_Hippy-Crusher-1.jpg' },
      { campId: 17, url: 'frontend/public/Images/campImages/17_Hippy-Crusher-2.jpg' },
      { campId: 18, url: 'frontend/public/Images/campImages/18_Aqueous-1.jpg' },
      { campId: 18, url: 'frontend/public/Images/campImages/18_Aqueous-2.jpg' },
      { campId: 18, url: 'frontend/public/Images/campImages/18_Aqueous-3.jpg' },
      { campId: 19, url: 'frontend/public/Images/campImages/19_Bloom.jpg' },
      { campId: 20, url: 'frontend/public/Images/campImages/20_Thunderdome-1.jpg' },
      { campId: 20, url: 'frontend/public/Images/campImages/20_Thunderdome-2.jpg' },
      { campId: 21, url: 'frontend/public/Images/campImages/21_Flower-Tower-1.jpg' },
      { campId: 21, url: 'frontend/public/Images/campImages/21_Flower-Tower-2.jpg' },
      { campId: 21, url: 'frontend/public/Images/campImages/21_Flower-Tower-3.jpg' },
      { campId: 22, url: 'frontend/public/Images/campImages/22_Temple-of-Awareness.jpg' },
      { campId: 23, url: 'frontend/public/Images/campImages/23_Firmament-1.jpg' },
      { campId: 23, url: 'frontend/public/Images/campImages/23_Firmament-2.jpg' },
      { campId: 23, url: 'frontend/public/Images/campImages/23_Firmament-3.jpg' },
      { campId: 24, url: 'frontend/public/Images/campImages/24_Sonic-Soul-Tribe-1.jpg' },
      { campId: 25, url: 'frontend/public/Images/campImages/25_White-Ocean-1.jpg' },
      { campId: 25, url: 'frontend/public/Images/campImages/25_White-Ocean-2.jpg' },
      { campId: 25, url: 'frontend/public/Images/campImages/25_White-Ocean-3.jpg' },
      { campId: 26, url: 'frontend/public/Images/campImages/26_Opulent-Temple-1.jpg' },
      { campId: 26, url: 'frontend/public/Images/campImages/26_Opulent-Temple-2.jpg' },
      { campId: 27, url: 'frontend/public/Images/campImages/27_The-Kazbah-1.jpg' },
      { campId: 28, url: 'frontend/public/Images/campImages/28_Robot-Heart-1.jpg' },
      { campId: 28, url: 'frontend/public/Images/campImages/28_Robot-Heart-2.jpg' },
      { campId: 13, url: 'frontend/public/Images/campImages/13_BM-2017-GIFs-1.gif' },
      { campId: 13, url: 'frontend/public/Images/campImages/13_BM-2017-GIFs-6.gif' },
      { campId: 13, url: 'frontend/public/Images/campImages/13_BM-2017-GIFs-7.gif' },
      { campId: 13, url: 'frontend/public/Images/campImages/13_BM-2017-GIFs-8.gif' },
      { campId: 14, url: 'frontend/public/Images/campImages/14_BM-2017-GIFs-2.gif' },
      { campId: 14, url: 'frontend/public/Images/campImages/14_BM-2017-GIFs-3.gif' },
      { campId: 15, url: 'frontend/public/Images/campImages/15_BM-2017-GIFs-4.gif' },
      { campId: 23, url: 'frontend/public/Images/campImages/23_BM-2017-GIFs-5.gif' },
    ], {});

  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Images', null, {});

  }
};
